spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/toollibrary}
    username: ${DATASOURCE_USERNAME:equipassa}
    password: ${DATASOURCE_PASSWORD:equipassa123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        default_schema: public
  flyway:
    schemas: public
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    user:
      name: admin
      password: securepassword
    oauth2:
      client:
        registration: { }
    filter:
      order: 0
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  
  main:
    banner-mode: off
    allow-circular-references: false

  cloud:
    aws:
      s3:
        path-style-access-enabled: true
      region:
        static: eu-central-1
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY:minioadmin}
        secret-key: ${AWS_S3_SECRET_KEY:minioadmin123}
      endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${EQUIPASSA_PORT:8081}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: INFO
        web: INFO
      hibernate: INFO
    com:
      equipassa: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

jwt:
  secret: ${JWT_SECRET:oanUY3TWtuwJKukAndKwb+DLt8/QtjS41zRuJJ8Ql8k=}
  expiration: ${JWT_EXPIRATION:3600000}
  extendedExpiration: ${JWT_EXTENDED_EXPIRATION:2592000000}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
    bucket: ${AWS_S3_BUCKET:equipassa}
    accessKey: ${AWS_S3_ACCESS_KEY:minioadmin}
    secretKey: ${AWS_S3_SECRET_KEY:minioadmin123}
    region: ${AWS_S3_REGION:hamburg}

equipassa:
  email:
    from-address: "no-replay@equipassa.com"
  server: ${EQUIPASSA_SERVER:http://localhost:8081}