spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ignore-me
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 0
      max-lifetime: 30000
      connection-timeout: 30000
      maximum-pool-size: 4
      minimum-idle: 0

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    schemas: public

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      region:
        static: eu-central-1
      credentials:
        access-key: minioadmin
        secret-key: minioadmin123
      s3:
        endpoint: http://localhost:9000
        bucket: equipassa-bucket-test

  main:
    banner-mode: off
    allow-circular-references: false

server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true

logging:
  level:
    root: WARN
    com.equipassa: INFO
    org.springframework: INFO

jwt:
  secret: test-secret-please-change
  expiration: 3600000
  extendedExpiration: 2592000000
  refreshExpiration: 604800000

equipassa:
  email:
    from-address: "no-reply@test.equipassa.com"
  server: http://localhost
