name: Renovate Verification
on:
  pull_request:
    paths:
      - 'pom.xml'
      - '**/pom.xml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build (no tests)
        run: mvn -B -ntp clean verify -DskipTests
        env:
          MAVEN_OPTS: "--enable-native-access=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED"
